"""
Oncology Clinical Assistant (Simulated)
----------------------------------------
Advanced version with:
  - Bilingual support (Hindi + English), auto-detected per message
  - Richer patient-context handling (diagnoses, treatments, allergies,
    upcoming appointments, vitals)
  - Defensive error handling with polite apology messages in both languages
    whenever expected data is missing or malformed

NOTE: All "extraction" and "chat" functions below are simulations for
demo/testing purposes. They do not perform real OCR or real clinical
reasoning, and none of this should be used for actual patient care.
"""

import re

CLINICAL_DISCLAIMER_EN = (
    "\n\n[Warning: This content is generated by AI. It is not medical advice. "
    "A licensed clinician must verify all recommendations and staging "
    "classifications before making clinical decisions.]"
)

CLINICAL_DISCLAIMER_HI = (
    "\n\n[चेतावनी: यह जानकारी AI द्वारा तैयार की गई है। यह चिकित्सीय सलाह नहीं है। "
    "किसी भी क्लिनिकल निर्णय से पहले एक लाइसेंस-प्राप्त चिकित्सक द्वारा सभी सिफारिशों और "
    "स्टेजिंग वर्गीकरण की पुष्टि आवश्यक है।]"
)

APOLOGY_EN = (
    "I'm sorry — I couldn't find that information in the chart, or something "
    "went wrong while processing it. "
)
APOLOGY_HI = (
    "क्षमा करें — मुझे चार्ट में यह जानकारी नहीं मिली, या इसे प्रोसेस करते समय कुछ गड़बड़ी हुई। "
)


# ---------------------------------------------------------------------------
# Language detection
# ---------------------------------------------------------------------------

_DEVANAGARI_RE = re.compile(r"[\u0900-\u097F]")

_HINGLISH_HINTS = {
    "kya", "hai", "hain", "kaise", "kab", "kaun", "kripya", "batao", "bataiye",
    "mujhe", "aap", "aapka", "iska", "uska", "dawai", "dawaai", "bimari",
    "ilaj", "report", "marij", "rogi",
}


def detect_language(message: str) -> str:
    """
    Returns 'hi' if the message looks like Hindi (Devanagari script or
    common Hinglish/romanized-Hindi words), otherwise 'en'.
    """
    if not message:
        return "en"
    if _DEVANAGARI_RE.search(message):
        return "hi"
    tokens = re.findall(r"[a-zA-Z]+", message.lower())
    hits = sum(1 for tok in tokens if tok in _HINGLISH_HINTS)
    # If a meaningful fraction of the words look like romanized Hindi, treat as Hindi
    if tokens and hits / len(tokens) >= 0.15:
        return "hi"
    return "en"


def disclaimer(lang: str) -> str:
    return CLINICAL_DISCLAIMER_HI if lang == "hi" else CLINICAL_DISCLAIMER_EN


def apology(lang: str) -> str:
    return APOLOGY_HI if lang == "hi" else APOLOGY_EN


# ---------------------------------------------------------------------------
# Simulated OCR / report extraction
# ---------------------------------------------------------------------------

def extract_report_text(report_type: str, file_name: str) -> str:
    """
    Simulates OCR extraction on medical documents, returning standard
    diagnostic narratives. Falls back gracefully with an apology if
    inputs are missing or malformed.
    """
    try:
        if not report_type or not isinstance(report_type, str):
            raise ValueError("report_type missing or invalid")
        if not file_name or not isinstance(file_name, str):
            raise ValueError("file_name missing or invalid")

        t = report_type.lower()
        if "pathology" in t:
            return (
                f"Pathology Report - Specimen: {file_name}\n"
                "Clinical History: Breast lump, outer upper quadrant.\n"
                "Gross Description: Sectioning reveals a firm, white mass measuring 2.1 x 1.8 cm.\n"
                "Microscopic Description: Sections show infiltrating ductal carcinoma (Grade II).\n"
                "Surgical Margins: Clear of tumor. Lymph nodes: 0/3 negative."
            )
        elif "radiology" in t or "ct" in t or "mri" in t:
            return (
                f"Radiology Scan - CT Thorax / Abdomen: {file_name}\n"
                "Indication: Staging for newly diagnosed lung adenocarcinoma.\n"
                "Findings: A 3.2 cm lobulated mass is seen in the right lower lobe.\n"
                "No hilar lymphadenopathy. Adrenals: normal size. Bone windows: normal.\n"
                "Impression: Primary lung neoplasm, no evidence of distant metastasis."
            )
        else:
            return (
                f"Laboratory Clinical Panel: {file_name}\n"
                "Complete Blood Count (CBC) and Metabolic Panel.\n"
                "White Blood Cells (WBC): 6.8 K/uL (Normal)\n"
                "Hemoglobin (Hgb): 13.2 g/dL (Normal)\n"
                "Platelets: 240 K/uL (Normal)\n"
                "Liver function enzymes within standard limits."
            )
    except Exception as exc:
        return (
            f"{APOLOGY_EN}(Technical detail: {exc})\n"
            f"{APOLOGY_HI}(तकनीकी विवरण: {exc})"
        )


def generate_report_summary(text: str, lang: str = "en") -> str:
    """
    Extracts staging parameters and primary sites to compile a concise,
    bilingual-labeled summary.
    """
    try:
        if not text or not isinstance(text, str):
            raise ValueError("no report text supplied")

        lines = text.split("\n")
        report_title = lines[0] if lines else "Medical Report Summary"

        primary_site = "Unknown Site"
        histology = "Unknown Histology"
        low = text.lower()
        if "breast" in low:
            primary_site = "Breast"
        elif "lung" in low or "thorax" in low:
            primary_site = "Lung"

        if "ductal" in low:
            histology = "Infiltrating Ductal Carcinoma"
        elif "adenocarcinoma" in low:
            histology = "Adenocarcinoma"

        if lang == "hi":
            summary = (
                f"**दस्तावेज़**: {report_title}\n"
                f"**प्राथमिक स्थान (Primary Site)**: {primary_site}\n"
                f"**हिस्टोलॉजी**: {histology}\n"
                f"**क्लिनिकल स्थिति**: सर्जिकल मार्जिन स्पष्ट। स्थानीयकृत गांठ, कोई मेटास्टेटिक विस्तार नहीं पाया गया।"
            )
        else:
            summary = (
                f"**Document**: {report_title}\n"
                f"**Primary Site**: {primary_site}\n"
                f"**Histology**: {histology}\n"
                f"**Clinical Status**: Specimen clear of surgical margins. Localized mass, no metastatic expansion noted."
            )
        return summary + disclaimer(lang)
    except Exception as exc:
        return apology(lang) + f"(detail / विवरण: {exc})" + disclaimer(lang)


# ---------------------------------------------------------------------------
# Bilingual chat assistant
# ---------------------------------------------------------------------------

def _safe_get(d: dict, key: str, default):
    try:
        val = d.get(key, default)
        return val if val not in (None, "") else default
    except Exception:
        return default


def generate_chat_response(message: str, patient_context: dict, lang: str = None) -> str:
    """
    RAG-simulated clinical chat answering patient-specific questions in
    English or Hindi. Language is auto-detected from `message` unless
    explicitly passed via `lang` ('en' or 'hi').
    """
    try:
        if lang not in ("en", "hi"):
            lang = detect_language(message)

        if not isinstance(patient_context, dict):
            raise ValueError("patient_context missing or malformed")

        msg = (message or "").lower()

        first_name = _safe_get(patient_context, "first_name", "the patient" if lang == "en" else "रोगी")
        last_name = _safe_get(patient_context, "last_name", "")
        full_name = f"{first_name} {last_name}".strip()
        gender = _safe_get(patient_context, "gender", "F")
        birth_date = _safe_get(patient_context, "birth_date", "N/A")
        status = _safe_get(patient_context, "status", "active")

        treatments = _safe_get(patient_context, "treatments", [])
        diagnoses = _safe_get(patient_context, "diagnoses", [])
        allergies = _safe_get(patient_context, "allergies", [])
        appointments = _safe_get(patient_context, "appointments", [])
        vitals = _safe_get(patient_context, "vitals", {})

        # --- Greeting -------------------------------------------------
        if any(g in msg for g in ["hello", "hi ", "hi", "namaste", "namaskar"]):
            if lang == "hi":
                return (
                    f"नमस्ते। मैं ऑन्कोलॉजी क्लिनिकल असिस्टेंट हूँ। मैंने {full_name} का चार्ट लोड कर लिया है। "
                    "मैं इलाज की जानकारी, क्लिनिकल टाइमलाइन, या रिपोर्ट सारांश में आपकी कैसे मदद कर सकता हूँ?"
                ) + disclaimer(lang)
            return (
                f"Hello. I am the Oncology Clinical Assistant. I have loaded the chart for {full_name}. "
                "How can I assist you with their treatment history, clinical timelines, or report summaries today?"
            ) + disclaimer(lang)

        # --- Treatments -------------------------------------------------
        if any(k in msg for k in ["treatment", "therapy", "ilaj", "dawai", "chikitsa"]):
            if not treatments:
                if lang == "hi":
                    return f"मुझे {full_name} के चार्ट में कोई सक्रिय या नियोजित इलाज योजना नहीं मिली।" + disclaimer(lang)
                return f"I see no active or planned treatment regimens logged in the chart for {full_name}." + disclaimer(lang)

            tx_list = []
            for t in treatments:
                if not isinstance(t, dict):
                    continue
                ttype = _safe_get(t, "type", "Unknown")
                tstart = _safe_get(t, "start_date", "N/A")
                tstatus = _safe_get(t, "status", "scheduled")
                tx_list.append(f"- {str(ttype).upper()} started on {tstart} ({tstatus})")
            tx_str = "\n".join(tx_list) if tx_list else "-"

            if lang == "hi":
                return (
                    f"{full_name} ({gender}, जन्म तिथि: {birth_date}) के लिए दर्ज उपचार योजनाएँ:\n\n"
                    f"{tx_str}\n\n"
                    "कृपया ध्यान दें: रेडियोथेरेपी योजनाएँ केवल शेड्यूलिंग दिखाती हैं। कोई सक्रिय रेडिएशन डोज़ ट्रैकिंग नहीं की जाती।"
                ) + disclaimer(lang)
            return (
                f"Here are the documented treatment plans for {full_name} ({gender}, DOB: {birth_date}):\n\n"
                f"{tx_str}\n\n"
                "Please note that radiotherapy plans only display scheduling modalities. No active radiation dose tracking is performed."
            ) + disclaimer(lang)

        # --- Diagnosis / staging -----------------------------------------
        if any(k in msg for k in ["diagnosis", "stage", "cancer", "bimari", "rog", "stej"]):
            if not diagnoses:
                if lang == "hi":
                    return f"मुझे {full_name} के लिए कोई स्टेजिंग रिकॉर्ड या प्राथमिक निदान नहीं मिला।" + disclaimer(lang)
                return f"I found no staging records or primary diagnoses logged for {full_name}." + disclaimer(lang)

            diag_list = []
            for d in diagnoses:
                if not isinstance(d, dict):
                    continue
                site = _safe_get(d, "primary_site", "N/A")
                hist = _safe_get(d, "histology", "N/A")
                ddate = _safe_get(d, "diagnosis_date", "N/A")
                diag_list.append(f"- {site} ({hist}) — diagnosed {ddate}")
            diag_str = "\n".join(diag_list) if diag_list else "-"

            if lang == "hi":
                return f"{full_name} के लिए दर्ज निदान:\n\n{diag_str}" + disclaimer(lang)
            return f"Documented diagnoses for {full_name}:\n\n{diag_str}" + disclaimer(lang)

        # --- Allergies -----------------------------------------------------
        if any(k in msg for k in ["allergy", "allergies", "elrji", "alarjee"]):
            if not allergies:
                if lang == "hi":
                    return f"{full_name} के चार्ट में कोई ज्ञात एलर्जी दर्ज नहीं है।" + disclaimer(lang)
                return f"No known allergies are logged for {full_name}." + disclaimer(lang)
            al_str = ", ".join(str(a) for a in allergies)
            if lang == "hi":
                return f"{full_name} की ज्ञात एलर्जी: {al_str}" + disclaimer(lang)
            return f"Known allergies for {full_name}: {al_str}" + disclaimer(lang)

        # --- Appointments ----------------------------------------------------
        if any(k in msg for k in ["appointment", "visit", "milne", "apwaintment", "checkup"]):
            if not appointments:
                if lang == "hi":
                    return f"{full_name} के लिए कोई आगामी अपॉइंटमेंट दर्ज नहीं है।" + disclaimer(lang)
                return f"No upcoming appointments are logged for {full_name}." + disclaimer(lang)
            appt_list = []
            for a in appointments:
                if not isinstance(a, dict):
                    continue
                adate = _safe_get(a, "date", "N/A")
                adoc = _safe_get(a, "with", "N/A")
                appt_list.append(f"- {adate} with {adoc}")
            appt_str = "\n".join(appt_list) if appt_list else "-"
            if lang == "hi":
                return f"{full_name} के आगामी अपॉइंटमेंट:\n\n{appt_str}" + disclaimer(lang)
            return f"Upcoming appointments for {full_name}:\n\n{appt_str}" + disclaimer(lang)

        # --- Vitals ------------------------------------------------------
        if any(k in msg for k in ["vitals", "bp", "blood pressure", "vaitals", "dhadkan"]):
            if not vitals:
                if lang == "hi":
                    return f"{full_name} के लिए कोई हालिया वाइटल्स दर्ज नहीं हैं।" + disclaimer(lang)
                return f"No recent vitals are logged for {full_name}." + disclaimer(lang)
            v_str = ", ".join(f"{k}: {v}" for k, v in vitals.items())
            if lang == "hi":
                return f"{full_name} के हालिया वाइटल्स: {v_str}" + disclaimer(lang)
            return f"Recent vitals for {full_name}: {v_str}" + disclaimer(lang)

        # --- Fallback -----------------------------------------------------
        if lang == "hi":
            return (
                f"मैंने {full_name} से संबंधित आपके प्रश्न का विश्लेषण किया है। "
                f"उनकी चार्ट स्थिति वर्तमान में '{status}' है। मैं कीमोथेरेपी शेड्यूल की जानकारी दे सकता हूँ या "
                "पैथोलॉजी रिपोर्ट का सारांश बना सकता हूँ, लेकिन मैं रियल-टाइम खुराक गणना या डायग्नोस्टिक स्टेजिंग "
                "घोषणाएँ नहीं कर सकता।"
            ) + disclaimer(lang)
        return (
            f"I've analyzed your question regarding {full_name}'s history. "
            f"Their current chart status is '{status}'. I can assist in mapping scheduled chemotherapy cycles or "
            "summarizing pathology reports, but I cannot make real-time dosage calculations or diagnostic staging "
            "declarations."
        ) + disclaimer(lang)

    except Exception as exc:
        # Bilingual apology whenever something goes wrong, regardless of
        # where in the flow the failure happened.
        safe_lang = lang if lang in ("en", "hi") else "en"
        return apology(safe_lang) + f"(detail / विवरण: {exc})" + disclaimer(safe_lang)


# ---------------------------------------------------------------------------
# Quick manual test (run this file directly to see sample output)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    demo_patient = {
        "first_name": "Anita",
        "last_name": "Sharma",
        "gender": "F",
        "birth_date": "1978-04-12",
        "status": "active",
        "diagnoses": [
            {"primary_site": "Breast", "histology": "Infiltrating Ductal Carcinoma", "diagnosis_date": "2025-11-02"}
        ],
        "treatments": [
            {"type": "chemotherapy", "start_date": "2025-11-20", "status": "ongoing"},
            {"type": "radiotherapy", "start_date": "2026-01-10", "status": "scheduled"},
        ],
        "allergies": ["Penicillin"],
        "appointments": [{"date": "2026-07-10", "with": "Dr. Rao (Oncology)"}],
        "vitals": {"BP": "118/76", "HR": "78 bpm", "SpO2": "98%"},
    }

    print(generate_chat_response("Namaste, iska ilaj kya chal raha hai?", demo_patient))
    print("\n---\n")
    print(generate_chat_response("What is the diagnosis for this patient?", demo_patient))
    print("\n---\n")
    print(generate_chat_response("kya koi allergy hai?", demo_patient))
    print("\n---\n")
    # Trigger a graceful, apologetic failure on purpose
    print(generate_chat_response("appointment kab hai?", None))