import os

CLINICAL_DISCLAIMER = (
    "\n\n[Warning: This content is generated by AI. It is not medical advice. "
    "A licensed clinician must verify all recommendations and staging classifications before making clinical decisions.]"
)

def extract_report_text(report_type: str, file_name: str) -> str:
    """
    Simulates OCR extraction on medical documents, returning standard diagnostic narratives.
    """
    t = report_type.lower()
    if "pathology" in t:
        return (
            f"Pathology Report - Specimen: {file_name}\n"
            "Clinical History: Breast lump, outer upper quadrant.\n"
            "Gross Description: Sectioning reveals a firm, white mass measuring 2.1 x 1.8 cm.\n"
            "Microscopic Description: Sections show infiltrating ductal carcinoma (Grade II).\n"
            "Surgical Margins: Clear of tumor. Lymph nodes: 0/3 negative."
        )
    elif "radiology" in t or "ct" in t or "mri" in t:
        return (
            f"Radiology Scan - CT Thorax / Abdomen: {file_name}\n"
            "Indication: Staging for newly diagnosed lung adenocarcinoma.\n"
            "Findings: A 3.2 cm lobulated mass is seen in the right lower lobe.\n"
            "No hilar lymphadenopathy. Adrenals: normal size. Bone windows: normal.\n"
            "Impression: Primary lung neoplasm, no evidence of distant metastasis."
        )
    else:
        return (
            f"Laboratory Clinical Panel: {file_name}\n"
            "Complete Blood Count (CBC) and Metabolic Panel.\n"
            "White Blood Cells (WBC): 6.8 K/uL (Normal)\n"
            "Hemoglobin (Hgb): 13.2 g/dL (Normal)\n"
            "Platelets: 240 K/uL (Normal)\n"
            "Liver function enzymes within standard limits."
        )

def generate_report_summary(text: str) -> str:
    """
    Extracts staging parameters and primary sites to compile a concise summary.
    """
    lines = text.split("\n")
    report_title = lines[0] if lines else "Medical Report Summary"
    
    # Parse simple clinical heuristics
    primary_site = "Unknown Site"
    histology = "Unknown Histology"
    if "breast" in text.lower():
        primary_site = "Breast"
    elif "lung" in text.lower() or "thorax" in text.lower():
        primary_site = "Lung"
        
    if "ductal" in text.lower():
        histology = "Infiltrating Ductal Carcinoma"
    elif "adenocarcinoma" in text.lower():
        histology = "Adenocarcinoma"

    summary = (
        f"**Document**: {report_title}\n"
        f"**Primary Site**: {primary_site}\n"
        f"**Histology**: {histology}\n"
        f"**Clinical Status**: Specimen clear of surgical margins. Localized mass, no metastatic expansion noted."
    )
    return summary + CLINICAL_DISCLAIMER

def generate_chat_response(message: str, patient_context: dict) -> str:
    """
    RAG-simulated clinical chat answering patient-specific questions.
    """
    msg = message.lower()
    first_name = patient_context.get("first_name", "the patient")
    last_name = patient_context.get("last_name", "")
    full_name = f"{first_name} {last_name}".strip()
    status = patient_context.get("status", "active")
    gender = patient_context.get("gender", "F")
    birth_date = patient_context.get("birth_date", "N/A")
    
    # Context elements
    treatments = patient_context.get("treatments", [])
    diagnoses = patient_context.get("diagnoses", [])
    
    if "hello" in msg or "hi" in msg:
        return (
            f"Hello. I am the Oncology Clinical Assistant. I have loaded the chart for {full_name}. "
            "How can I assist you with their treatment history, clinical timelines, or report summaries today?"
        ) + CLINICAL_DISCLAIMER

    if "treatment" in msg or "therapy" in msg:
        if not treatments:
            return f"I see no active or planned treatment regimens logged in the chart for {full_name}." + CLINICAL_DISCLAIMER
        
        tx_list = []
        for t in treatments:
            tx_list.append(f"- {t.get('type', 'Unknown').upper()} started on {t.get('start_date', 'N/A')} ({t.get('status', 'scheduled')})")
        tx_str = "\n".join(tx_list)
        return (
            f"Here are the documented treatment plans for {full_name} ({gender}, DOB: {birth_date}):\n\n"
            f"{tx_str}\n\n"
            "Please note that radiotherapy plans only display scheduling modalities. No active radiation dose tracking is performed."
        ) + CLINICAL_DISCLAIMER

    if "diagnosis" in msg or "stage" in msg or "cancer" in msg:
        if not diagnoses:
            return f"I found no staging records or primary diagnoses logged for {full_name}." + CLINICAL_DISCLAIMER
        
        diag_list = []
        for d in diagnoses:
            diag_list.append(f"- Diagnosis Site: {d.get('primary_site', 'N/A')} ({d.get('histology', 'N/A')}) diagnosed on {d.get('diagnosis_date', 'N/A')}")
        diag_str = "\n".join(diag_list)
        return (
            f"Documented diagnoses for {full_name}:\n\n"
            f"{diag_str}"
        ) + CLINICAL_DISCLAIMER

    # Fallback to general oncologist assistant answer
    return (
        f"I've analyzed your question regarding {full_name}'s history. "
        "Their current chart status is active. I can assist in mapping scheduled chemotherapy cycles or summarizing "
        "pathology reports, but I cannot make real-time dosage calculations or diagnostic staging declarations."
    ) + CLINICAL_DISCLAIMER
